### ISSUE TITLE
how to added fixed address and channel

### ISSUE THREAD

**Issue by cyberumut** [nopnop2002/esp-idf-sx127x#10]
how to added fixed address and channel ? 

i need address & channel 
as in the picture
![image](https://user-images.githubusercontent.com/105754498/225991844-2114696d-9406-4662-94eb-fe26c9045a5d.png)

**Comment by nopnop2002** [comment]
Where is your drawing from?


I can't find it in the SX1276/77/78/79 datasheet.

**Comment by cyberumut** [comment]
ebyte modules
Isn't this header structure global?
targetAddr | TargetChannel | Data 
how can i  apply this on sx1278
> Where is your drawing from?
> 
> I can't find it in the SX1276/77/78/79 datasheet.

**Comment by nopnop2002** [comment]
Where can I get your documentation?

tell me the url.


this is LoRa Packet Structure


![LoRa](https://user-images.githubusercontent.com/6020549/226054511-7591ef3b-082e-4305-b6df-0bffe0058516.jpg)

**Comment by cyberumut** [comment]
https://www.cdebyte.com/products/E22-400T30D/4#Downloads

check it manual .pdf 
> LoRa Packet Structure

**Comment by nopnop2002** [comment]
EBYTE's E22 module uses different frequencies depending on the channel.


![LoRa-2](https://user-images.githubusercontent.com/6020549/226057994-a20ac575-b9a6-4abd-bb6c-b0f8ac589e17.jpg)



you can use any frequency you like in menuconfig

![LoLa-3](https://user-images.githubusercontent.com/6020549/226058011-cdef7f9d-2c99-4bb3-b296-ccaa37b5821e.jpg)

**Comment by cyberumut** [comment]
module in hand is sx1278 ,not ebyte module
I want to define address and channel on sx1278
how can i do ? 

> EBYTE's E22 module uses different frequencies depending on the channel.
> 
> ![LoRa-2](https://user-images.githubusercontent.com/6020549/226057994-a20ac575-b9a6-4abd-bb6c-b0f8ac589e17.jpg)
> 
> you can use any frequency you like in menuconfig
> 
> ![LoLa-3](https://user-images.githubusercontent.com/6020549/226058011-cdef7f9d-2c99-4bb3-b296-ccaa37b5821e.jpg)

**Comment by nopnop2002** [comment]
This diagram you showed is from EBYTE.


![225991844-2114696d-9406-4662-94eb-fe26c9045a5d](https://user-images.githubusercontent.com/6020549/226059779-fa1a1769-e67d-45c6-aaf5-7f4e62dc7f11.png)

You're using EBYTE's SX1278, right?

**Comment by cyberumut** [comment]
no i dont using eybte module .
I just want to set up addressing and channel structure like it

> This diagram you showed is from EBYTE.
> 
> ![225991844-2114696d-9406-4662-94eb-fe26c9045a5d](https://user-images.githubusercontent.com/6020549/226059779-fa1a1769-e67d-45c6-aaf5-7f4e62dc7f11.png)
> 
> You're using EBYTE's SX1278, right?

**Comment by nopnop2002** [comment]
The LoRa specification does not have channels or addresses.

EBYTE modules channel is same as frequency



For modules other than EBYTE, change the frequency if you use the concept of channels.

___I recommend reading the SX1278 datasheet.___

**Comment by cyberumut** [comment]
If we add such a structure to the header. I think it can work if we parse the header on the other device or 
i selected channel 4  
Frequency= 410.125 + CH * 1M    
410.125+ 4*1M
using channel 414.125 example .
it needs to be calculated
![image](https://user-images.githubusercontent.com/105754498/226061129-6fce1704-f6ad-498f-b5ee-301e618ab396.png)

> The LoRa specification does not have channels or addresses.
> 
> EBYTE modules channel is same as frequency
> 
> For modules other than EBYTE, change the frequency if you use the concept of channels.

**Comment by nopnop2002** [comment]
I do not understand your content.

The LoRa packet structure is the following structure and Header is optional.

The LoRa packet structure and header content are strictly specified and cannot be changed.


![LoRa](https://user-images.githubusercontent.com/6020549/226061985-e6be99f1-54d4-4cf3-8888-6f08367ae02f.jpg)

```
Header
Depending upon the chosen mode of operation two types of header are available. The header type is selected by the
ImplicitHeaderModeOn bit found within the RegModemConfig1 register.

Explicit Header Mode
This is the default mode of operation. Here the header provides information on the payload, namely:
 The payload length in bytes.
 The forward error correction code rate
 The presence of an optional 16-bits CRC for the payload.
The header is transmitted with maximum error correction code (4/8). It also has its own CRC to allow the receiver to
discard invalid headers.



Implicit Header Mode
In certain scenarios, where the payload, coding rate and CRC presence are fixed or known in advance, it may be
advantageous to reduce transmission time by invoking implicit header mode. In this mode the header is removed from the
packet. In this case the payload length, error coding rate and presence of the payload CRC must be manually configured
on both sides of the radio link.
Note With SF = 6 selected, implicit header mode is the only mode of operation possible.
```

**Comment by nopnop2002** [comment]
EBYTE LoRa modules and non-EBYTE LoRa modules may not be able to communicate with each other.


This is because EBYTE has the concept of addresses, but LoRa modules other than EBYTE do not.

Presumably the EBYTE address is sent as part of the LoRa payload.
This is an EBYTE-specific payload.

EBYTE-specific payloads cannot be interpreted correctly by non-EBYTE LoRa modules.

**Comment by cyberumut** [comment]
i got it now thank u bro
> EBYTE LoRa modules and non-EBYTE LoRa modules may not be able to communicate with each other.
> 
> This is because EBYTE has the concept of addresses, but LoRa modules other than EBYTE do not.
> 
> Presumably the EBYTE address is sent as part of the LoRa payload. This is an EBYTE-specific payload.
> 
> EBYTE-specific payloads cannot be interpreted correctly by non-EBYTE LoRa modules.
