### ISSUE TITLE
RA01S: WaitForIdle Timeout timeout=5000

### ISSUE THREAD

**Issue by pluzmedia** [nopnop2002/esp-idf-sx127x#12]
Hi,

Encountered the "RA01S: WaitForIdle Timeout timeout=5000" error randomly during operation. How to restart it?

Thanks

**Comment by nopnop2002** [comment]
>Encountered the "RA01S: WaitForIdle Timeout timeout=5000" error randomly during operation.

RA01S is SX126X, not SX127X.
You are using the wrong library.
