### ISSUE TITLE
Which sx127*  module ?

### ISSUE THREAD

**Issue by netmonk** [nopnop2002/esp-idf-sx127x#3]
Hello, which SX127* module are you using for dev this library ? 
i guess hoperf rfm95 or any board with an esp32 and lora module like Liligo.

Why i ask ? Because im looking for support of EbYTES sx1276/78 modules like E19-868M30S
Those modules are designed with some added pin like TXEN/RXEN that must be respetively HIGH when sending or receiving.
But i never see ESP-IDF library which implement this.

**Comment by netmonk** [comment]
I played with two lora liligo lora32 modules and both basic/pingpong are working fine.
Congratulation, now is time to test esp32c3 and Ebyte E19 modules.

**Comment by netmonk** [comment]
![Screenshot from 2022-02-15 23-29-27](https://user-images.githubusercontent.com/3428684/154160592-8ec589ed-3b54-4b22-9039-37eefeeb063e.png)

**Comment by netmonk** [comment]
Funny the second partner seems to have received some other lora packet (may be my gateway ttn) 
![Screenshot from 2022-02-15 23-34-25](https://user-images.githubusercontent.com/3428684/154161366-0421797e-b515-4e26-b03f-f9de7fe0cf77.png)

**Comment by netmonk** [comment]
Btw, 60 to 70 ms of back to back time is like 16hz
Expresslrs on same hardware reach easely 100hz up to 250hz on 868/915 
it can reach 500hz packet rate using 2.4ghz lora modules

**Comment by nopnop2002** [comment]
Hello.
Thank you for your PR.

>Hello, which SX127* module are you using for dev this library ?

I used these:
https://www.aliexpress.com/item/32911759847.html?spm=a2g0o.9042311.0.0.27424c4dL4D3Cc
https://www.aliexpress.com/item/32962551530.html?spm=a2g0o.9042311.0.0.6aa24c4dHXeafK

>it can reach 500hz packet rate using 2.4ghz lora modules

SX1280 is a bit expensive. So I don't have it.
I don't think the SX1280 is compatible with the SX127X.
I think the SX1280 has the same specifications as the SX126X.

I am currently ordering the SX1262.

I'm not sure if the E19-868M30S can be used with a pin pitch of 2.54 millimeters.
There may be a pitch conversion board for E19-868M30S somewhere.

**Comment by netmonk** [comment]
The EBYTE E28 https://www.ebyte.com/en/product-view-news.html?id=537
is like the Ebyte E22 very small pinout module.
I made an expension board for the E22 Module same can be done for the E28 Module :
![photo_2022-01-12_13-49-42](https://user-images.githubusercontent.com/3428684/154214241-a33ac2d1-bad7-408f-8fcd-fa80f14a525d.jpg)
And sx1280 like sx1262 are new generation transceivers from semtech that's right.

**Comment by nopnop2002** [comment]
>I made an expension board for the E22 Modul

I want it.....


I think EBYTE should officially support such an expension board.

**Comment by netmonk** [comment]
Send email to netmonk-at-netmonk dot org with your adress i will send some sample. Beware it’s pin labelled for  E22

**Comment by nopnop2002** [comment]
Thank you for your offer.

If you sell this on ebay, I will buy it.

**Comment by netmonk** [comment]
https://easyeda.com/dpac/e22-carrier-board 
You can find the open design here. My proposition was to send you a vrigin pcb board for free.
I can also send a mounted board (need to have two in order to test new feature such has SF 5 ) far free. :)

I just checked and E22/E28 are not compatibles in pin design.

**Comment by nopnop2002** [comment]
>My proposition was to send you a vrigin pcb board for free.

Really?

**Comment by netmonk** [comment]
Yes

**Comment by nopnop2002** [comment]
You need Shipping Cost.
Are you OK?

**Comment by netmonk** [comment]
I appreciate you worry about that but don't :)
I prefer being paid in answering my stupid question than getting money this has more value to me :)

**Comment by nopnop2002** [comment]
I sent mail to you.
Thank you again.

**Comment by netmonk** [comment]
im not sure you click "send" i received nothing

**Comment by nopnop2002** [comment]
I made a mistake.

I sent it again.

**Comment by netmonk** [comment]
Great received :)

**Comment by nopnop2002** [comment]
When I receive the extension board, I would like to hear your opinion on which communication module it is worth testing.

I have never used EBYTE's communication module.

**Comment by netmonk** [comment]
Did you receive anything  by airmail ?

**Comment by nopnop2002** [comment]
No.

Probably the influence of Ukraine.

**Comment by netmonk** [comment]
Hello did you receive it ?

**Comment by nopnop2002** [comment]
No.
